### PR TITLE
reviewed to improve performances

### PR DESCRIPTION
**Pull request by 1C0D**

### CODE REVIEW

**Comment by 1C0D** [comment]
Hi I did a method taking more into consideration only 1 edge by loop

**Comment by vilemduha** [comment]
Hi! sorry, just noticed this. Can we call so you could explain me what are all the changes? WIll be happy to merge.

**Comment by 1C0D** [comment]
this is to improve performances try it on a quite heavy mesh to see the difference

**Comment by vilemduha** [comment]
Just merged it, thanks!

**Pull request merged**
